spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_app:3306/mysqlDb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
  sql.init.mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
