version: "3.1"

services:
  es:
    image: elasticsearch:7.17.7
    container_name: es
    restart: always
    environment:
      - node.name=single-node
      - discovery.type=single-node
      - cluster.name=${CLUSTER_NAME}
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge
    volumes:
      - ${DIR_MOUNTED}:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: kibana:7.17.7
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge
